
# default values for genetic algorithms
DEFAULT_CROSSOVER_RATE = 0.1
DEFAULT_MUTATION_RATE  = 0.3
DEFAULT_PERTURBATION_RATE = 0.4
DEFAULT_NUMBER_SAMPLE_POINTS = 1000
DEFAULT_GENERATION_SIZE = 200
DEFAULT_ELITE_SIZE = 10
